--USUARIOS
INSERT INTO usuarios(email, username, password) VALUES('pablo@gmail.com', 'pablo', '$2a$10$3Xh/E6BcbaNLiIlGE6EMxesbqRfS7/RWavl6gYkRsRjjdfKJuXdHi')
INSERT INTO usuarios(email, username, password) VALUES('pepe@gmail.com', 'pepe', '$2a$10$3Xh/E6BcbaNLiIlGE6EMxesbqRfS7/RWavl6gYkRsRjjdfKJuXdHi')

INSERT INTO ROLES(rol) VALUES('ROLE_ADMIN')
INSERT INTO ROLES(rol) VALUES('ROLE_USER')

INSERT INTO USUARIOS_ROLES(USUARIO_ID, ROL_ID) VALUES(1, 1)
INSERT INTO USUARIOS_ROLES(USUARIO_ID, ROL_ID) VALUES(1, 2)
INSERT INTO USUARIOS_ROLES(USUARIO_ID, ROL_ID) VALUES(2, 2)

--HORARIOS

INSERT INTO HORARIOS(HORA) VALUES('8:00')
INSERT INTO HORARIOS(HORA) VALUES('9:00')
INSERT INTO HORARIOS(HORA) VALUES('10:00')
INSERT INTO HORARIOS(HORA) VALUES('11:00')
INSERT INTO HORARIOS(HORA) VALUES('12:00')
INSERT INTO HORARIOS(HORA) VALUES('13:00')
INSERT INTO HORARIOS(HORA) VALUES('14:00')
INSERT INTO HORARIOS(HORA) VALUES('15:00')
INSERT INTO HORARIOS(HORA) VALUES('16:00')
INSERT INTO HORARIOS(HORA) VALUES('17:00')
INSERT INTO HORARIOS(HORA) VALUES('18:00')
INSERT INTO HORARIOS(HORA) VALUES('19:00')
INSERT INTO HORARIOS(HORA) VALUES('20:00')
INSERT INTO HORARIOS(HORA) VALUES('21:00')
INSERT INTO HORARIOS(HORA) VALUES('22:00')